### ISSUE TITLE
Can you please add the training script as well? 

### ISSUE THREAD

**Issue by Bozorgtabar** [lmb-freiburg/hand3d#1]

**Comment by zimmerm** [comment]
Unfortunately the collection of scripts used for training are not well documented and rather specific to the cluster system used. But I'll keep the request in mind for future releases, which follow as soon as I get back working on this project.

**Comment by handale88** [comment]
@zimmerm Thank you for this testing hand pose estimation code. Could you tell me when it will be the time you would be able to share the training script as well?
