### ISSUE TITLE
is there a way to extract your predicted keypoints

### ISSUE THREAD

**Issue by coldgemini** [lmb-freiburg/hand3d#10]
is there a way to extract your predicted keypoints

**Comment by Franziska-Mueller** [comment]
When you check the run.py file, you can see that the predictions are obtained in line 62:
keypoints_scoremap_v, keypoint_coord3d_v = sess.run(...)

Note that the score maps are the complete score/heat maps so the function "detect_keypoints" in line 73 is applied to obtain the 2D u,v coordinate prediction.

**Comment by zimmerm** [comment]
Thank you for answering that Franziska :)
