### ISSUE TITLE
A question about handsegnet

### ISSUE THREAD

**Issue by Sakuralala** [lmb-freiburg/hand3d#11]
Hey,I read the handsegnet part of your code,but after that ,I have a question.That is: in your paper,you said,
"Our HandSegNet is a smaller version of the network from Wei et al. [19] trained on our hand pose dataset. ".
But in your code,I think you just did the first half part like the method in "Fully Convolutional Networks for Semantic Segmentation"(FCN),the hand masks is not the same as heatmaps,at least in my opinion.Is my understanding right?

**Comment by zimmerm** [comment]
I used the network from Wei and initialized with their weights. I removed a couple of layers and retrained it for hand segmentation. So yes it is different from a tasks point of view. I'm training it for semantic segmentation and not regression of score maps.
