### ISSUE TITLE
Is there a trained caffe model?

### ISSUE THREAD

**Issue by jasminezz** [lmb-freiburg/hand3d#12]
Thanks for your works.
I have trained on tensorflow successfully, Do you have the trained caffe model?
If you do not have the plan to convert the model to caffe, do you have some suggestions that I should pay attention when  trained on caffe?

**Comment by zimmerm** [comment]
I only used Tensorflow so I can't help you with any caffe related issues. 
But its possible to convert caffe networks to tensorflow, so the other way should be possible too. Maybe you can find some insights here: https://github.com/ethereon/caffe-tensorflow
