### ISSUE TITLE
how fast is it?

### ISSUE THREAD

**Issue by dedoogong** [lmb-freiburg/hand3d#13]
can I get any inference speed measurments? can it be poosible to run on TX2 in real time?

**Comment by zimmerm** [comment]
I can run the RGB -> 3D pipeline on an GTX 1080 Ti at 0.026sec per iteration, which equals ~ 38fps. Time for loading, writing or visualizing data is excluded. Unfortunately I can't provide the runtime on a TX2.

**Comment by julianweisbord** [comment]
Can you share the code that you used to achieve 38 fps? I copied run.py and made a few adjustments to work with opencv and my webcam but I am only getting 5 fps on a GTX 1080 TI.

**Comment by vasanthhr** [comment]
@zimmerm / @julianweisbord 

I am running on G3.4xLarge instance(high performance GPU from AWS), but run.py execution time takes close to 6 seconds per image. Please look into this below issue and help me if i am doing anything wrong here.


Could you please help me on this issue, I am going though same issue now:

https://github.com/lmb-freiburg/hand3d/issues/25
