### ISSUE TITLE
is there a custom layer?

### ISSUE THREAD

**Issue by dedoogong** [lmb-freiburg/hand3d#14]
I would like to start to port it to caffe(My goal is to implement just forward passes, not for training).

I have read your paper roughly and I wonder there are some custom layers which are not included in the existing TF or caffe layers. 

Plus, I wonder, HandSegNet can be replaced with SSD hand detector as I thought HandSegNet is just for detecting hands and after that the hand-cropped patchs from the original image(not from the feature map of the last layer of the HandSegNet) is transferred to PoseNet.

**Comment by dedoogong** [comment]
Sorry but I have one more question. the pretrained weights are all saved in pickel format. But I need ckpt to convert to caffemodel format or pb format. Can I use tf.train.Saver().save to re-save the model after loading the pickle weights?

**Comment by zimmerm** [comment]
I didn't implement any custom operations  for Tensorflow. So you can use a off the stock Tensorflow version.

Indeed you can replace HandSegNet with any other detection algorithm. 

Yes, you can save the weights into a checkpoint after you initialized them from the pickle.
