### ISSUE TITLE
How can I use only './weights/posenet3d-rhd-stb-slr-finetuned.pickle'?

### ISSUE THREAD

**Issue by dedoogong** [lmb-freiburg/hand3d#15]
when I use only the model "'./weights/posenet3d-rhd-stb-slr-finetuned.pickle'", 
I got one error "ValueError: cannot reshape array of size 1049600 into shape (2562,512)"
Hmmm, 2562 x 512 is 1311744 and 1049600 = 2050 x 512. What should I do?
It seems to be related to PosePrior/fc_rel0/weights's shape " 2050, 512 = 1049600.
I think I should call _inference_pose3d() as PosePrior, ViewPointNet's parameters are contained in the pickle and it was loaded already. 

I don't use HandSegNet as below;
    def inference(self, image, hand_side, evaluation):
        
        # detect keypoints in 2D
        keypoints_scoremap = self.inference_pose2d(image) 
        keypoints_scoremap = keypoints_scoremap[-1] 
        # estimate most likely 3D pose
        keypoint_coord3d = self._inference_pose3d(keypoints_scoremap, hand_side, evaluation) 
        # upsample keypoint scoremap 
        s = image.get_shape().as_list()
        keypoints_scoremap = tf.image.resize_images(keypoints_scoremap, (s[1], s[2])) 
        return image, keypoints_scoremap

Can anybody give me any hint? Please help me ;/

**Comment by zimmerm** [comment]
I guess your variable _image_ does not have size (B, 256, 256, 3).

**Comment by dedoogong** [comment]
thanks ! you're right. I didn't think about it ;/ sorry.

**Comment by dedoogong** [comment]
I'm still trying to solve it and I just didn't use build up step as below because I can read the pre-built graph from the pb file. 

    image_crop_tf = tf.placeholder(tf.float32, shape=(1, 256, 256, 3))
    keypoints_scoremap_tf = tf.placeholder(tf.float32, shape=(1, 256, 256, 21))
    # build network
    #net = ColorHandPose3DNetwork()
    #image_crop_tf, keypoints_scoremap_tf= net.inference(image_tf, hand_side_tf, evaluation)
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.3)
    with tf.Session(config=tf.ConfigProto(gpu_options=gpu_options)) as sess:
        #net.init(sess)
        model_filename = '/home/lee/Downloads/Classify-HandGesturePose-master/posemodel/frozen_model.pb'
        with tf.gfile.GFile(model_filename, "rb") as f:
            graph_def = tf.GraphDef()
            graph_def.ParseFromString(f.read())
        with tf.Graph().as_default() as graph:
            tf.import_graph_def(graph_def)
            image_tf = graph.get_tensor_by_name('import/Placeholder:0')
            #y = graph.get_tensor_by_name('import/MatMul:0')
        checkpoint_path = tf.train.latest_checkpoint("./posemodel/")
        saver = tf.train.import_meta_graph(checkpoint_path + ".meta", import_scope=None)
        saver.restore(sess, checkpoint_path)

        image_list.append('./data/test.png')
        image_list.append('./data/test2.png')
        image_list.append('./data/test3.png')
        for img_name in image_list:
            image_raw = scipy.misc.imread(img_name)
            image_raw = scipy.misc.imresize(image_raw, (256,256))
            image_v = np.expand_dims((image_raw.astype('float') / 255.0) - 0.5, 0)
            image_crop_v, keypoints_scoremap_v = sess.run([image_crop_tf, keypoints_scoremap_tf], feed_dict={image_tf: image_v})

I could successfully get image_tf by calling graph.get_tensor_by_name('import/Placeholder:0')
but image_crop_v, keypoints_scoremap_v = sess.run([image_crop_tf, keypoints_scoremap_tf], feed_dict={image_tf: image_v})
makes an error;
TypeError: Cannot interpret feed_dict key as Tensor: Tensor Tensor("import/Placeholder:0", shape=(1, 256, 256, 3), dtype=float32) is not an element of this graph.
why this happened? 
Even I got image_tf from pb graph correctly...but why it failed in finding the image_tf Tensor in the graph?
Can anybody help me?
