### ISSUE TITLE
Forward pass?

### ISSUE THREAD

**Issue by jayala** [lmb-freiburg/hand3d#17]
Hello,
what does the forward pass weights contains? Was it trained with the whole RHD dataset for handsegnet and posenet? Because it says minimal example should I download the dataset  and retrain all?

**Comment by zimmerm** [comment]
Hi,
for running the minimal example you dont need to download the dataset. Only
download the network weights.

**Comment by jayala** [comment]
Oh, yeah I did that. Got interesting results with the forward pass, but somehow it sometimes confuses lips with hands.

[https://image.ibb.co/cz5OD0/outoutx-out.png](https://image.ibb.co/cz5OD0/outoutx-out.png)

Do you think this there is something wrong with my setup?

**Comment by zimmerm** [comment]
No not necessarily. Truthfully, It is not the strongest pose estimator out there anymore and the behavior you describes partially stems from its assumption that there is always a hand present in the image.

**Comment by jayala** [comment]
Yeah, that's what I thought too. Well, will try some of the other projects out there. Thank you @zimmerm
