### ISSUE TITLE
Problem during training

### ISSUE THREAD

**Issue by momo1986** [lmb-freiburg/hand3d#20]
When running with ,,python  training_handsegnet.py"
it reported error:
"
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on ./weights/cpm-model-mpii: Not found: ./weights; No such file or directory."

From the paper, some design idea come from open-pose, could you guide me where is the essential pre-downloaded model for training, e.g., cpm-model-mpii.

Thanks & Regards！
Neo

**Comment by zimmerm** [comment]
Usually, following the steps pointed out in this Repos Readme help.
https://github.com/lmb-freiburg/hand3d#usage-forward-pass
