### ISSUE TITLE
Can I use training_lifting.py for my custom dataset?

### ISSUE THREAD

**Issue by JasOlean** [lmb-freiburg/hand3d#21]
I used another hand detector and keypoints detector. After that, I want to use your training_lifting.py to lift 2D to 3D coordinates. So, can I use only your posepriornetwork for 3D pose estimation. How can I do that?

And in your posenet network, what kinds of output of keypoints_map. As example, 21 keypoints for one image or all images. Can you show me your keypoints_map result as an example?

**Comment by zimmerm** [comment]
If your keypoint detector sticks to the same definition of keypoints it might be able to use the lifting components separately
