### ISSUE TITLE
Converting to Java (Android)

### ISSUE THREAD

**Issue by slimcdk** [lmb-freiburg/hand3d#24]
Hello!

I'm wokring on a academic project (bachelor) where I need to estimate a hands skeleton in 3D!
You work looks very interesting and I would like to use it as my backend for estimating hand skeletons. 

I see it is built on top of tensorflow, so how difficult would this be to export to Java? E.g. Tensorflow Lite? I guess it still calls some of the native C++ functions.

Best regards,
Christian!

**Comment by zimmerm** [comment]
Unfortunately, I dont have any experiences in porting tensorflow models to Java, so I'm afraid I cant help you here.
