### ISSUE TITLE
Processing Frames(images) in run.py is very slow on GPU (G3.4xLarge EC2 Instance)

### ISSUE THREAD

**Issue by vasanthhr** [lmb-freiburg/hand3d#25]
Hello Team,

I tried to run the run.py file for the various images and the images that provided by you in the folder "data". But the execution time is more for each images. And processing image and getting result itself taking more time and its taking close to "6 seconds per image".

Even I tried tensorflow, and tensoflow-gpu and G3 AWS instance(It has below graphic card) , but no luck in execution time.

Graphic card details:

```
00:02.0 VGA compatible controller: Cirrus Logic GD 5446
00:1e.0 VGA compatible controller: NVIDIA Corporation GM204GL [Tesla M60] (rev a1)

```

(Main goal is to explore this runi.py for live webcam video , but please help me reduce the execution time)

Please find installed packages:

```
absl-py==0.7.1
bleach==1.5.0
cycler==0.10.0
html5lib==0.9999999
Markdown==3.0.1
matplotlib==1.5.3
numpy==1.16.2
Pillow==5.4.1
pkg-resources==0.0.0
protobuf==3.7.0
pyparsing==2.3.1
python-dateutil==2.8.0
pytz==2018.9
scipy==0.18.1
six==1.12.0
tensorflow-gpu==1.5.0
tensorflow-tensorboard==1.5.1
Werkzeug==0.15.1
```

Code where I am checking execution time in run.py:

```

        t = time.time()
        print("Intial taken : {:.3f}".format(time.time() - t))

        hand_scoremap_v, image_crop_v, scale_v, center_v,\
        keypoints_scoremap_v, keypoint_coord3d_v = sess.run([hand_scoremap_tf, image_crop_tf, scale_tf, center_tf,
                                                             keypoints_scoremap_tf, keypoint_coord3d_tf],
                                                            feed_dict={image_tf: image_v})

        print("time taken by network : {:.3f}".format(time.time() - t))
```

Result:  for this below images

    image_list.append('./data/img3.png')
    image_list.append('./data/img4.png')
    image_list.append('./data/img5.png')

```
Intial taken : 0.000
time taken by network : 5.537
Intial taken : 0.000
time taken by network : 5.338
Intial taken : 0.000
time taken by network : 5.340
```

**Comment by zimmerm** [comment]
@vasanthhr I copy pasted your code and ran it on my desktop machine and it evaluates to:
time taken by network 1.795
time taken by network 0.053
time taken by network 0.053
time taken by network 0.059
time taken by network 0.061

Not sure what the problem is in your case and unfortunately I don't have access to AWS.
