### ISSUE TITLE
Could you provide the weights files whcih generated by pickle dump in protocol 2 ?

### ISSUE THREAD

**Issue by kyodaisuki** [lmb-freiburg/hand3d#3]
I had download the data files, weights_HandSegNet.pickle and weights_Pose3D.pickle.
I encountered the error "ValueError: unsupported pickle protocol: 3" when using the python 2.7.
The tensorflow package installed on my python 2.7,and I know that probably I reinstall tensorflow on python 3.5 maybe solve the issue.
If you help me provide the weights files  generated by pickle dump in protocol 2, it will help me a lot.

Thanks

**Comment by zimmerm** [comment]
I added the converted weights to the up to date data archive and replaced the link in the description.
[Here](https://lmb.informatik.uni-freiburg.de/projects/hand3d/ColorHandPose3D_data_v2.zip) is the archive, which contains the python2 compatible pickles.

**Comment by kyodaisuki** [comment]
thank you!
