### ISSUE TITLE
Visible meaning in RHD

### ISSUE THREAD

**Issue by nitba** [lmb-freiburg/hand3d#32]
Hi @zimmerm ,

in `RHD` dataset what does `visible` mean? does it mean to be occluded or not 
Or does it mean the existence of hand (joint) in image?

**Comment by zimmerm** [comment]
Visible is determined based on a heuristic that evaluates the number of hand segmentation pixels in a neighborhood around the projected keypoint. So it should evaluate to false if the point is outside the image frame or the neighborhood is occupied by a segmentation class that is not related to the keypoint in question.
