### ISSUE TITLE
how to make mask image from the hand color image

### ISSUE THREAD

**Issue by handale88** [lmb-freiburg/hand3d#6]
With your RHD DB, you have mask images from color image. Could you tell me how to make mask image?
I would like to make the similar dataset from the custom dataset as well.

**Comment by zimmerm** [comment]
I'm not sure what you are asking for, but I created my dataset with Blender and used a specific render pass to create the segmentation masks. But you need mesh models and the mapping from mesh vertices to classes in order to do so.
